name: Test on macos-14 runner

on: workflow_dispatch

jobs:
  compiled-macos-arm64:
    ## macos-14 is a m1 runner
    runs-on: macos-14
    timeout-minutes: 5
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
        
      - name: Download V
        run: |
          git clone https://github.com/vlang/v
          cd v
          make
          sudo ./v symlink
          
      - name: Run fetch example
        run: |
          cd v/examples
          v -cc tcc fetch.v
          
#      - name: Run example
#        run: v -cc clang example.v
